# Generated by Django 6.1.1 on 2026-09-29 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failure', 'Не успешно')], max_length=10, verbose_name='статус')),
                ('server_response', models.TextField(blank=True, verbose_name='ответ почтового сервера')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='mailings.client', verbose_name='получатель')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailings.mailing', verbose_name='рассылка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='mailings.mailingattempt', verbose_name='попытка запуска')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылок',
                'ordering': ['-attempted_at', '-pk'],
            },
        ),
    ]
